from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^orders-requests/$",
        views.orders_and_accepted_requests,
        name="orders_and_requests"),
    url(r"^orders-requests/history/$",
        views.orders_and_requests_history,
        name="orders_and_requests_history"),
    url(r"^orders/(?P<order_id>[0-9]+)/cancel/$", views.cancel_order),
    url(r"^orders/(?P<order_id>[0-9]+)/feedback/$",
        views.order_feedback,
        name="feedback"),
    url(r"^orders/(?P<order_id>[0-9]+)/feedback/complain/$",
        views.order_complain),
    url(r"^orders/(?P<order_id>[0-9]+)/feedback/follow/$",
        views.order_follow),
    url(r"^posts/$", views.posts),
    url(r"^posts/manage/$", views.manage_posts, name="manage_posts"),
    url(r"^posts/manage/(?P<dish_post_id>[0-9]+)/$",
        views.manage_post_detail,
        name="manage_post_detal"),
    url(r"^posts/manage/(?P<dish_post_id>[0-9]+)/bids/(?P<bid_id>[0-9]+)/reject/$",
        views.reject_bid),
    url(r"^posts/manage/(?P<dish_post_id>[0-9]+)/bids/(?P<bid_id>[0-9]+)/accept/$",
        views.accept_bid),
    url(r"^posts/manage/orders/(?P<order_id>[0-9]+)/rate/$",
        views.rate_diner),
    url(r"^posts/create/$", views.create_post),
    url(r"^dish_suggestions/$", views.suggest_dishes),
    url(r"^posts/(?P<dish_post_id>[0-9]+)/$", views.post_detail),
    url(r"^posts/(?P<dish_post_id>[0-9]+)/order/$", views.order_dish),
    url(r"^posts/(?P<dish_post_id>[0-9]+)/cancel/$", views.cancel_post),
    url(r"^posts/(?P<dish_post_id>[0-9]+)/edit/$", views.edit_post),
    url(r"^requests/$", views.requests, name="list-requests"),
    url(r"^requests/create/$", views.create_request),
    url(r"^requests/manage/$", views.manage_open_requests, name="manage_requests"),
    url(r"^requests/(?P<dish_request_id>[0-9]+)/$",
        views.request_detail,
        name="request_detail"),
    url(r"^requests/(?P<dish_request_id>[0-9]+)/cancel/$", views.cancel_request),
    url(r"^chefs/(?P<chef_id>[0-9]+)/$", views.chef_detail, name="chef_detail"),
    url(r"^chefs/(?P<chef_id>[0-9]+)/history/$", views.chef_history, name="chef_history"),
    url(r"^chefs/(?P<chef_id>[0-9]+)/edit/$", views.edit_chef),
    url(r"^requests/(?P<dish_request_id>[0-9]+)/edit/$", views.edit_request, name="requests"),
    url(r"^requests/(?P<dish_request_id>[0-9]+)/offers/$",
        views.request_offers,
        name="requests_offers"),
    url(r"^requests/(?P<dish_request_id>[0-9]+)/offers/(?P<offer_id>[0-9]+)/reject/$",
        views.reject_offer),
    url(r"^requests/(?P<dish_request_id>[0-9]+)/offers/(?P<offer_id>[0-9]+)/accept/$",
        views.accept_offer),
    url(r"^chefs/(?P<chef_id>[0-9]+)/rate/$", views.rate_chef),
    url(r"^requests/(?P<dish_request_id>[0-9]+)/rate/$", views.rate_diner),
]
